version: "3.7"

services:
  php:
    build:
      args:
        user: cris
        uid: 1000
      context: .
      dockerfile: ./config/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/
    hostname: wunderkammer.local

